name: 'my_project'
version: '1.0.0'
config-version: 2

profile: 'my_project'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_project:
    materialized: view
    staging:
      materialized: view
    marts:
      materialized: table

vars:
  my_var: 'my_value'

require-dbt-version: [">=1.0.0", "<2.0.0"]