version: 2

sources:
  - name: dev
    database: db
    tables:
      - name: raw_earthquake_data
        columns:
          - name: id
            # description: "Unique identifier for each earthquake event."
          - name: magnitude
            # description: "Magnitude of the earthquake."
          - name: location
            # description: "Geographical location of the earthquake."
          - name: depth
            # description: "Depth at which the earthquake occurred."
          - name: event_time
            # description: "Timestamp of when the earthquake event occurred."
        # description: "Raw earthquake data ingested from external sources."
     