version: 2

sources:
  - name: dev
    tables:
      - name: raw_earthquake_data
        description: "Raw earthquake data from USGS API format=csv"
        columns:
          - name: id
            description: "Primary key from USGS"
          - name: magnitude
          - name: latitude
          - name: longitude
          - name: depth
          - name: location
          - name: time
            description: "Raw timestamp string from API"