#!/bin/bash
set -euo pipefail

: "${POSTGRES_USER:?Missing POSTGRES_USER}"
: "${POSTGRES_DB:?Missing POSTGRES_DB}"
: "${AIRFLOW_DB_USER:?Missing AIRFLOW_DB_USER}"
: "${AIRFLOW_DB_PASSWORD:?Missing AIRFLOW_DB_PASSWORD}"
: "${AIRFLOW_DB_NAME:?Missing AIRFLOW_DB_NAME}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
-- Create role if missing
SELECT 'CREATE ROLE ${AIRFLOW_DB_USER} LOGIN PASSWORD ''${AIRFLOW_DB_PASSWORD}''' 
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${AIRFLOW_DB_USER}')
\gexec

-- Create database if missing
SELECT 'CREATE DATABASE ${AIRFLOW_DB_NAME} OWNER ${AIRFLOW_DB_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${AIRFLOW_DB_NAME}')
\gexec

GRANT ALL PRIVILEGES ON DATABASE ${AIRFLOW_DB_NAME} TO ${AIRFLOW_DB_USER};
EOSQL
