#!/bin/bash
set -euo pipefail

: "${POSTGRES_USER:?Missing POSTGRES_USER}"
: "${POSTGRES_DB:?Missing POSTGRES_DB}"
: "${SUPERSET_DB_USER:?Missing SUPERSET_DB_USER}"
: "${SUPERSET_DB_PASSWORD:?Missing SUPERSET_DB_PASSWORD}"
: "${SUPERSET_DB_NAME:?Missing SUPERSET_DB_NAME}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
-- Create role if missing
SELECT 'CREATE ROLE ${SUPERSET_DB_USER} LOGIN PASSWORD ''${SUPERSET_DB_PASSWORD}''' 
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${SUPERSET_DB_USER}')
\gexec

-- Create database if missing
SELECT 'CREATE DATABASE ${SUPERSET_DB_NAME} OWNER ${SUPERSET_DB_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${SUPERSET_DB_NAME}')
\gexec

GRANT ALL PRIVILEGES ON DATABASE ${SUPERSET_DB_NAME} TO ${SUPERSET_DB_USER};
EOSQL
